import AppKit
import Combine
import CryptoKit

enum ClipboardContent: Equatable {
    case text(String)
    /// Guardamos os bytes (para colar de volta) e uma miniatura (para desenhar).
    case image(data: Data, thumbnail: NSImage, pixels: NSSize)
    case files([URL])
}

struct ClipboardItem: Identifiable, Equatable {
    let id = UUID()
    let content: ClipboardContent
    /// Impressão digital do conteúdo — é por ela que deduplicamos, já que
    /// comparar NSImage por identidade deixaria repetir a mesma imagem.
    let signature: String
    let date: Date

    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        lhs.signature == rhs.signature
    }

    var preview: String {
        switch content {
        case .text(let texto):
            return texto.split(separator: "\n", omittingEmptySubsequences: true)
                .first
                .map { $0.trimmingCharacters(in: .whitespaces) } ?? texto
        case .image(_, _, let pixels):
            return "Imagem \(Int(pixels.width))×\(Int(pixels.height))"
        case .files(let urls):
            return urls.count == 1
                ? urls[0].lastPathComponent
                : "\(urls.count) arquivos"
        }
    }
}

/// Histórico do que passou pela área de transferência: texto, imagens e arquivos.
///
/// Fica só em memória, de propósito: histórico de cópia guarda senha, token e
/// mensagem privada, e gravar isso em disco cria um problema que o app não
/// precisa ter. Também respeitamos as marcações que gerenciadores de senha usam
/// para dizer "não guarde".
@MainActor
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private static let maxItems = 25
    /// Imagem grande na área de transferência é comum (print de tela inteira);
    /// guardar muitas encheria a memória à toa.
    private static let maxImagens = 6
    private static let maxBytesPorImagem = 16 * 1024 * 1024
    /// A cada quantos ticks do timer de 30 Hz olhamos o contador (~0,6 s).
    private static let ticksEntreLeituras = 20

    /// Começa inválido de propósito: o que já está copiado agora é a entrada
    /// mais recente do histórico, e ignorá-lo faria o app parecer quebrado
    /// logo depois de abrir.
    private var lastChangeCount = -1
    private var tickAtual = 0

    private static let tiposIgnorados: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Não existe notificação de mudança da área de transferência; o jeito é
    /// olhar o contador. Ler ele é barato e pega carona no timer do mouse.
    func tick() {
        tickAtual += 1
        guard tickAtual % Self.ticksEntreLeituras == 0 else { return }
        capturar()
    }

    private func capturar() {
        let quadro = NSPasteboard.general
        guard quadro.changeCount != lastChangeCount else { return }
        lastChangeCount = quadro.changeCount

        let tipos = Set(quadro.types ?? [])
        guard tipos.isDisjoint(with: Self.tiposIgnorados) else { return }
        guard let novo = leiaConteudo(de: quadro) else { return }
        guard items.first?.signature != novo.signature else { return }

        items.removeAll { $0.signature == novo.signature }
        items.insert(novo, at: 0)
        podar()
    }

    /// Ordem importa: um arquivo copiado no Finder também traz o caminho como
    /// texto, e uma imagem às vezes vem junto de um nome. O mais específico ganha.
    private func leiaConteudo(de quadro: NSPasteboard) -> ClipboardItem? {
        let opcoes: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = quadro.readObjects(forClasses: [NSURL.self], options: opcoes) as? [URL],
           !urls.isEmpty {
            let assinatura = "files:" + urls.map(\.path).joined(separator: "|")
            return ClipboardItem(content: .files(urls), signature: assinatura, date: Date())
        }

        if let dados = quadro.data(forType: .png) ?? quadro.data(forType: .tiff),
           dados.count <= Self.maxBytesPorImagem,
           let imagem = NSImage(data: dados), imagem.size.width > 0 {
            return ClipboardItem(
                content: .image(
                    data: dados,
                    thumbnail: Self.miniatura(de: imagem),
                    pixels: Self.tamanhoEmPixels(de: imagem)),
                signature: "image:" + Self.digest(dados),
                date: Date())
        }

        if let texto = quadro.string(forType: .string),
           !texto.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipboardItem(content: .text(texto), signature: "text:" + texto, date: Date())
        }

        return nil
    }

    private func podar() {
        if items.count > Self.maxItems {
            items.removeLast(items.count - Self.maxItems)
        }
        // Imagens saem primeiro por peso, não por idade.
        var imagensVistas = 0
        items.removeAll { item in
            guard case .image = item.content else { return false }
            imagensVistas += 1
            return imagensVistas > Self.maxImagens
        }
    }

    /// Devolve o item para a área de transferência, no tipo original.
    func copy(_ item: ClipboardItem) {
        let quadro = NSPasteboard.general
        quadro.clearContents()

        switch item.content {
        case .text(let texto):
            quadro.setString(texto, forType: .string)
        case .image(let dados, _, _):
            quadro.setData(dados, forType: .png)
        case .files(let urls):
            quadro.writeObjects(urls.map { $0 as NSURL })
        }

        // Não registra de volta como se fosse uma cópia nova.
        lastChangeCount = quadro.changeCount
        if let indice = items.firstIndex(of: item), indice != 0 {
            items.remove(at: indice)
            items.insert(item, at: 0)
        }
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items.removeAll()
    }

    // MARK: - Auxiliares

    private static func digest(_ dados: Data) -> String {
        SHA256.hash(data: dados).prefix(8).map { String(format: "%02x", $0) }.joined()
    }

    private static func tamanhoEmPixels(de imagem: NSImage) -> NSSize {
        for representacao in imagem.representations {
            let largura = representacao.pixelsWide
            let altura = representacao.pixelsHigh
            if largura > 0, altura > 0 {
                return NSSize(width: largura, height: altura)
            }
        }
        return imagem.size
    }

    private static func miniatura(de imagem: NSImage, lado: CGFloat = 44) -> NSImage {
        let original = imagem.size
        guard original.width > 0, original.height > 0 else { return imagem }
        let escala = min(lado / original.width, lado / original.height, 1)
        let novo = NSSize(width: original.width * escala, height: original.height * escala)

        let resultado = NSImage(size: novo)
        resultado.lockFocus()
        imagem.draw(in: NSRect(origin: .zero, size: novo))
        resultado.unlockFocus()
        return resultado
    }
}
